/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: {
    Start: ['README'],
    HyperDB: [
      'HyperDB/Overview',
      'HyperDB/Architecture',
      'HyperDB/LocalFirstApi',
      'HyperDB/ApiReference',
      'HyperDB/ReactIntegration',
      'HyperDB/Examples',
      'HyperDB/ExpoSetup',
      'HyperDB/MigrationGuide',
      'HyperDB/PeerSyncSecurity',
      'HyperDB/Publishing',
      'HyperDB/Troubleshooting',
    ],
    Project: ['EnhancedFork'],
    Installation: [
      'EnhancedInstall',
      'Installation',
      'Setup',
      'Schema',
      'Model',
      'Advanced/Migrations',
    ],
    Usage: ['Relation', 'CRUD', 'Components', 'Query', 'Reactive', 'Writers'],
    Sync: [
      'Sync/Intro',
      'Sync/Frontend',
      'Sync/PeerToPeer',
      'Sync/Backend',
      'Sync/Limitations',
      'Sync/FAQ',
      'Sync/Troubleshoot',
      'Sync/Contribute',
    ],
    WatermelonCore: [
      'Advanced/CreateUpdateTracking',
      'Advanced/AdvancedFields',
      'Advanced/Flow',
      'Advanced/LocalStorage',
      'Advanced/ProTips',
      'Advanced/Performance',
      'Advanced/SharingDatabaseAcrossTargets',
    ],
    Contributing: [
      {
        type: 'autogenerated',
        dirName: 'Implementation',
      },
    ],
    Other: ['Roadmap', 'CONTRIBUTING', 'CHANGELOG'],
  },
}

module.exports = sidebars
