// @noflow

import fs from 'fs'
import path from 'path'

import { normalizeModels } from '../modeling'
import { ensureDir, loadModule, resolveExport, timestampId, writeIfChanged } from './utils'
import { createSnapshot, loadSnapshot, snapshotFingerprint } from './snapshot'
import { diffSnapshots } from './diff'
import { emitSchemaFile } from './emitSchema'
import { emitTypesFile } from './emitTypes'
import { emitHooksFile } from './emitHooks'
import { emitModelFile } from './emitModels'
import { formatBlockedChangesError, loadMigrationMap, planMigrations } from './migrationPlanner'

export type GenerateOptions = {
  cwd?: string,
  modelsPath?: string,
  outDir?: string,
  migrationMapPath?: string,
  snapshotPath?: string,
  migrationsDir?: string,
  logger?: (message: string) => void,
}

export type GenerateResult = {
  changedFiles: string[],
  snapshotPath: string,
  schemaVersion: number,
  hasChanges: boolean,
}

const defaultModelsPath = 'hypertill/models.ts'
const defaultOutDir = 'hypertill/generated'
const defaultMigrationMapPath = 'hypertill/hypertill.migration-map.ts'
const defaultMigrationMapPathJs = 'hypertill/hypertill.migration-map.js'

const resolveModels = (loaded: any): any[] => {
  const exported = resolveExport(loaded)

  if (Array.isArray(exported)) {
    return exported
  }

  if (exported && Array.isArray(exported.models)) {
    return exported.models
  }

  throw new Error(
    `[HyperTillDB] Models file must export either default ModelDefinition[] or { models: ModelDefinition[] }`,
  )
}

const emitMigrationFile = ({
  schemaVersion,
  migrationSteps,
}: {
  schemaVersion: number,
  migrationSteps: any[],
}): string => {
  const body = JSON.stringify(
    {
      toVersion: schemaVersion,
      steps: migrationSteps,
    },
    null,
    2,
  )

  return `// Generated by HyperTillDB.\nexport const migration = ${body} as const\n\nexport default migration\n`
}

const emitIndexFile = (models: any[]): string => {
  const modelExports = models.map((model) => `export { default as ${model.name} } from './models/${model.name}'`)
  return `${modelExports.join('\n')}\n`
}

export const generate = (options: GenerateOptions = {}): GenerateResult => {
  const cwd = options.cwd || process.cwd()
  const modelsPath = path.resolve(cwd, options.modelsPath || defaultModelsPath)
  const outDir = path.resolve(cwd, options.outDir || defaultOutDir)
  const migrationMapPath = path.resolve(cwd, options.migrationMapPath || defaultMigrationMapPath)
  const snapshotPath = path.resolve(cwd, options.snapshotPath || path.join(outDir, 'model-snapshot.json'))
  const migrationsDir = path.resolve(cwd, options.migrationsDir || path.join(outDir, 'migrations'))
  const logger = options.logger || (() => {})

  if (!fs.existsSync(modelsPath)) {
    throw new Error(`[HyperTillDB] Could not find models file at ${modelsPath}`)
  }

  const loadedModels = resolveModels(loadModule(modelsPath))
  const models = normalizeModels(loadedModels)

  const previousSnapshot = loadSnapshot(snapshotPath)
  const previousFingerprint = previousSnapshot ? snapshotFingerprint(previousSnapshot) : null

  const tentativeSchemaVersion = previousSnapshot ? previousSnapshot.schemaVersion + 1 : 1
  const tentativeSnapshot = createSnapshot(models, tentativeSchemaVersion)
  const diff = diffSnapshots(previousSnapshot, tentativeSnapshot)

  if (!diff.hasChanges && previousSnapshot) {
    logger(`[HyperTillDB] No model changes detected. Output is already up to date.`)
    return {
      changedFiles: [],
      snapshotPath,
      schemaVersion: previousSnapshot.schemaVersion,
      hasChanges: false,
    }
  }

  const resolvedMigrationMapPath = fs.existsSync(migrationMapPath)
    ? migrationMapPath
    : options.migrationMapPath
      ? migrationMapPath
      : path.resolve(cwd, defaultMigrationMapPathJs)
  const migrationMap = loadMigrationMap(resolvedMigrationMapPath)
  const migrationPlan = planMigrations(diff, migrationMap)

  if (migrationPlan.blockedDestructiveChanges.length > 0) {
    throw formatBlockedChangesError(migrationPlan.blockedDestructiveChanges, resolvedMigrationMapPath)
  }

  const schemaVersion = previousSnapshot ? previousSnapshot.schemaVersion + 1 : 1
  const snapshot = createSnapshot(models, schemaVersion)
  const nextFingerprint = snapshotFingerprint(snapshot)

  if (previousFingerprint === nextFingerprint && previousSnapshot) {
    return {
      changedFiles: [],
      snapshotPath,
      schemaVersion,
      hasChanges: false,
    }
  }

  ensureDir(outDir)
  ensureDir(path.join(outDir, 'models'))
  ensureDir(migrationsDir)

  const changedFiles = []

  const schemaFile = path.join(outDir, 'schema.ts')
  if (writeIfChanged(schemaFile, emitSchemaFile(models, schemaVersion))) {
    changedFiles.push(schemaFile)
  }

  const typesFile = path.join(outDir, 'types.ts')
  if (writeIfChanged(typesFile, emitTypesFile(models))) {
    changedFiles.push(typesFile)
  }

  const hooksFile = path.join(outDir, 'hooks.ts')
  if (writeIfChanged(hooksFile, emitHooksFile(models))) {
    changedFiles.push(hooksFile)
  }

  const modelsIndexFile = path.join(outDir, 'models', 'index.ts')
  if (writeIfChanged(modelsIndexFile, emitIndexFile(models))) {
    changedFiles.push(modelsIndexFile)
  }

  models.forEach((model) => {
    const modelFile = path.join(outDir, 'models', `${model.name}.ts`)
    if (writeIfChanged(modelFile, emitModelFile(model))) {
      changedFiles.push(modelFile)
    }
  })

  if (migrationPlan.shouldWriteMigration) {
    const migrationFile = path.join(migrationsDir, `${timestampId()}.ts`)
    fs.writeFileSync(
      migrationFile,
      emitMigrationFile({ schemaVersion, migrationSteps: migrationPlan.migrationSteps }),
    )
    changedFiles.push(migrationFile)
  }

  const snapshotContent = `${JSON.stringify(snapshot, null, 2)}\n`
  if (writeIfChanged(snapshotPath, snapshotContent)) {
    changedFiles.push(snapshotPath)
  }

  logger(`[HyperTillDB] Generated ${changedFiles.length} files`) // eslint-disable-line no-console
  return {
    changedFiles,
    snapshotPath,
    schemaVersion,
    hasChanges: true,
  }
}

export default generate
