import * as core from './core'

export {
  defineModel,
  dbModel,
  defineModels,
  normalizeModels,
  string,
  number,
  boolean,
  json,
  relation,
  toSnakeCase,
  createHyperTill,
  createDB,
} from './hypertill'

export type {
  JsonValue,
  RowShape,
  RelationDescriptor,
  DBModelOptions,
  DBModel,
  DefinedModelEntry,
  DefinedModels,
  RelationHelper,
  SystemColumns,
  WithSystemColumns,
  MutationProgress,
  MutationResult,
  ModelAPI,
  DBClient,
  CreateDBOptions,
  CreateSchemaDBOptions,
  SchemaDBClient,
  ModelDefinition,
  ModelField,
  FieldBuilder,
  InternalFieldSpec,
  InferModelInput,
  InferModelRow,
  HyperTillClient,
  HyperTillModelApi,
  QueryConfig,
  CreateHyperTillOptions,
} from './hypertill'

export { core }

export {
  Collection,
  Database,
  Relation,
  Model,
  associations,
  Query,
  tableName,
  columnName,
  appSchema,
  tableSchema,
  localStorageKey,
  createReactiveClient,
  uuidv4,
  setIdGenerator,
  useUuidV4IdGenerator,
  Q,
} from './core'

export type {
  CollectionMap,
  LocalStorageKey,
  DatabaseAdapter,
  RawRecord,
  DirtyRaw,
  RecordId,
  TableName,
  ColumnName,
  ColumnType,
  ColumnSchema,
  TableSchema,
  AppSchema,
  SchemaMigrations,
  ReactiveClient,
  ReactiveClientOptions,
  ReactiveTableQuery,
  ReactiveResponse,
  ReactiveOrderOptions,
  ReactiveUpsertOptions,
  IdGenerator,
} from './core'
