// @flow

import * as core from './core'

export {
  defineModel,
  dbModel,
  defineModels,
  normalizeModels,
  string,
  number,
  boolean,
  json,
  relation,
  toSnakeCase,
  createHyperTill,
  createDB,
  createSchemaSnapshot,
  planSchemaMigration,
  formatMigrationBlockedError,
} from './hypertill'

export { core }

// Transitional aliases to keep import friction low while v2 becomes primary.
export {
  Collection,
  Database,
  Relation,
  Model,
  associations,
  Query,
  tableName,
  columnName,
  appSchema,
  tableSchema,
  localStorageKey,
  createReactiveClient,
  uuidv4,
  setIdGenerator,
  useUuidV4IdGenerator,
  Q,
} from './core'

export type {
  CollectionMap,
  LocalStorageKey,
  DatabaseAdapter,
  RawRecord,
  DirtyRaw,
  RecordId,
  TableName,
  ColumnName,
  ColumnType,
  ColumnSchema,
  TableSchema,
  AppSchema,
  SchemaMigrations,
  ReactiveClient,
  ReactiveClientOptions,
  ReactiveTableQuery,
  ReactiveResponse,
  ReactiveOrderOptions,
  ReactiveSearchOptions,
  ReactiveUpsertOptions,
  IdGenerator,
} from './core'

export type {
  RelationDescriptor,
  DBModelOptions,
  DBModel,
  DefinedModelEntry,
  DefinedModels,
  QueryOperator,
  SearchMode,
  SearchOptions,
  MutationProgress,
  MutationResult,
  BulkWriteOptions,
  CreateDBOptions,
  SchemaSnapshotColumn,
  SchemaSnapshotTable,
  SchemaSnapshot,
  MigrationBlockedChange,
  MigrationPlan,
  MigrationOptions,
  ModelDefinition,
  ModelField,
  FieldBuilder,
  InternalFieldSpec,
  HyperTillClient,
  HyperTillModelApi,
  QueryConfig,
  CreateHyperTillOptions,
} from './hypertill'
